import PDFDocument from "pdfkit";

export const generateDailyReportPDF = async (dateStr, logs, requestorName) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: "A4" });
    const buffers = [];

    doc.on("data", (chunk) => buffers.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(buffers)));
    doc.on("error", reject);

    const pageWidth = doc.page.width; // 595
    const margin = 40;
    const contentWidth = pageWidth - margin * 2; // 515

    // ─── Header Banner ──────────────────────────────────────────────────────
    doc.rect(0, 0, pageWidth, 80).fill("#1e1b4b");
    doc
      .fontSize(20)
      .font("Helvetica-Bold")
      .fillColor("#ffffff")
      .text("Daily Attendance Report", margin, 18, {
        align: "center",
        width: contentWidth,
      });
    doc
      .fontSize(8.5)
      .font("Helvetica")
      .fillColor("#a5b4fc")
      .text(
        `Date: ${dateStr || "All Time"}  |  Generated by: ${requestorName}  |  ${new Date().toLocaleString()}`,
        margin,
        50,
        { align: "center", width: contentWidth }
      );

    let y = 100;

    // ─── Summary Boxes ────────────────────────────────────────────────────────
    const total = logs.length;
    const completed = logs.filter((l) => l.completionStatus === "completed").length;
    const incomplete = total - completed;

    const boxH = 38;
    const boxW = (contentWidth - 20) / 3;

    [
      { label: "Total Records", value: total, color: "#6366f1" },
      { label: "Completed", value: completed, color: "#10b981" },
      { label: "Incomplete", value: incomplete, color: "#f59e0b" },
    ].forEach((item, i) => {
      const bx = margin + i * (boxW + 10);
      // border
      doc.rect(bx, y, boxW, boxH).fillAndStroke("#f8fafc", item.color);
      doc
        .fontSize(18)
        .font("Helvetica-Bold")
        .fillColor(item.color)
        .text(String(item.value), bx, y + 4, { width: boxW, align: "center" });
      doc
        .fontSize(7)
        .font("Helvetica")
        .fillColor("#64748b")
        .text(item.label, bx, y + 24, { width: boxW, align: "center" });
    });

    y += boxH + 18;

    // ─── Empty state ──────────────────────────────────────────────────────────
    if (logs.length === 0) {
      doc.rect(margin, y, contentWidth, 60).fill("#f8fafc");
      doc
        .fontSize(11)
        .font("Helvetica")
        .fillColor("#94a3b8")
        .text("No attendance records found for this date.", margin, y + 22, {
          align: "center",
          width: contentWidth,
        });
      doc.end();
      return;
    }

    // ─── Table columns ────────────────────────────────────────────────────────
    const cols = [
      { key: "employee",   label: "EMPLOYEE",   x: margin,       w: 115 },
      { key: "punchIn",    label: "PUNCH IN",   x: margin + 115, w: 55  },
      { key: "punchOut",   label: "PUNCH OUT",  x: margin + 170, w: 55  },
      { key: "hours",      label: "HOURS",      x: margin + 225, w: 40  },
      { key: "validation", label: "VALIDATION", x: margin + 265, w: 65  },
      { key: "status",     label: "STATUS",     x: margin + 330, w: 75  },
      { key: "remark",     label: "REMARK",     x: margin + 405, w: 110 },
    ];

    const headerH = 20;
    const rowH = 34;

    const drawHeader = (startY) => {
      doc.rect(margin, startY, contentWidth, headerH).fill("#1e293b");
      doc.fontSize(7.5).font("Helvetica-Bold").fillColor("#e2e8f0");
      cols.forEach((col) => {
        doc.text(col.label, col.x + 3, startY + 5, {
          width: col.w - 5,
          lineBreak: false,
        });
      });
      return startY + headerH;
    };

    y = drawHeader(y);

    // ─── Rows ─────────────────────────────────────────────────────────────────
    logs.forEach((log, idx) => {
      if (y + rowH > doc.page.height - 50) {
        doc.addPage();
        y = 40;
        y = drawHeader(y);
      }

      const bg = idx % 2 === 0 ? "#f8fafc" : "#ffffff";
      doc.rect(margin, y, contentWidth, rowH).fill(bg);

      // Employee name + email
      const empName = log.employeeId?.name || "Unknown";
      const empEmail = log.employeeId?.email || "";
      doc
        .fontSize(8)
        .font("Helvetica-Bold")
        .fillColor("#0f172a")
        .text(empName, cols[0].x + 3, y + 6, {
          width: cols[0].w - 6,
          lineBreak: false,
        });
      doc
        .fontSize(6.5)
        .font("Helvetica")
        .fillColor("#64748b")
        .text(empEmail, cols[0].x + 3, y + 18, {
          width: cols[0].w - 6,
          lineBreak: false,
        });

      // Punch In
      const punchInTime = log.punchIn?.time
        ? new Date(log.punchIn.time).toLocaleTimeString("en-IN", {
            hour: "2-digit",
            minute: "2-digit",
            hour12: true,
          })
        : "-";
      doc
        .fontSize(8)
        .font("Helvetica")
        .fillColor("#0f172a")
        .text(punchInTime, cols[1].x + 3, y + 12, {
          width: cols[1].w - 5,
          lineBreak: false,
        });

      // Punch Out
      const punchOutTime = log.punchOut?.time
        ? new Date(log.punchOut.time).toLocaleTimeString("en-IN", {
            hour: "2-digit",
            minute: "2-digit",
            hour12: true,
          })
        : "-";
      doc.text(punchOutTime, cols[2].x + 3, y + 12, {
        width: cols[2].w - 5,
        lineBreak: false,
      });

      // Hours
      const hours = log.workingHours ? `${log.workingHours.toFixed(2)}h` : "-";
      doc.text(hours, cols[3].x + 3, y + 12, {
        width: cols[3].w - 5,
        lineBreak: false,
      });

      // Validation status (coloured)
      const validation = log.validation?.status || "pending";
      const valColor =
        validation === "valid"
          ? "#10b981"
          : validation === "invalid"
          ? "#ef4444"
          : "#f59e0b";
      doc
        .fillColor(valColor)
        .text(validation.toUpperCase(), cols[4].x + 3, y + 12, {
          width: cols[4].w - 5,
          lineBreak: false,
        });

      // Completion status (coloured)
      const status = log.completionStatus || "incomplete";
      const statusColor = status === "completed" ? "#10b981" : "#f59e0b";
      doc
        .fillColor(statusColor)
        .text(status.toUpperCase(), cols[5].x + 3, y + 12, {
          width: cols[5].w - 5,
          lineBreak: false,
        });

      // Remark
      const remark = log.validation?.remarks || log.remarks || "-";
      doc
        .fontSize(7)
        .fillColor("#475569")
        .text(remark, cols[6].x + 3, y + 6, {
          width: cols[6].w - 6,
          height: rowH - 10,
          ellipsis: true,
        });

      // Row divider
      doc
        .moveTo(margin, y + rowH)
        .lineTo(margin + contentWidth, y + rowH)
        .strokeColor("#e2e8f0")
        .lineWidth(0.5)
        .stroke();

      y += rowH;
    });

    // ─── Footer ───────────────────────────────────────────────────────────────
    y += 14;
    doc
      .fontSize(7.5)
      .font("Helvetica-Oblique")
      .fillColor("#94a3b8")
      .text(
        `Total ${logs.length} record(s) — Attendance Management System`,
        margin,
        y,
        { align: "center", width: contentWidth }
      );

    doc.end();
  });
};
