import PDFDocument from "pdfkit";

export const generateDailyReportPDF = async (dateStr: string, logs: any[], requestorName: string): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: "A4" });
    const buffers: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => buffers.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(buffers)));
    doc.on("error", reject);

    const pageWidth = doc.page.width; // 595
    const margin = 40;
    const contentWidth = pageWidth - margin * 2; // 515

    // ─── Header Banner ──────────────────────────────────────────────────────
    doc.rect(0, 0, pageWidth, 80).fill("#1e1b4b");
    doc
      .fontSize(20)
      .font("Helvetica-Bold")
      .fillColor("#ffffff")
      .text("Daily Attendance Report", margin, 18, {
        align: "center",
        width: contentWidth,
      });
    doc
      .fontSize(8.5)
      .font("Helvetica")
      .fillColor("#a5b4fc")
      .text(
        `Date: ${dateStr || "All Time"}  |  Generated by: ${requestorName}  |  ${new Date().toLocaleString()}`,
        margin,
        50,
        { align: "center", width: contentWidth }
      );

    let y = 100;

    // ─── Empty state ──────────────────────────────────────────────────────────
    if (logs.length === 0) {
      doc.rect(margin, y, contentWidth, 60).fill("#f8fafc");
      doc
        .fontSize(11)
        .font("Helvetica")
        .fillColor("#94a3b8")
        .text("No attendance records found for this date.", margin, y + 22, {
          align: "center",
          width: contentWidth,
        });
      doc.end();
      return;
    }

    // ─── Table columns ────────────────────────────────────────────────────────
    const cols = [
      { key: "employee",   label: "EMPLOYEE",   x: margin,       w: 115 },
      { key: "punchIn",    label: "PUNCH IN",   x: margin + 115, w: 55  },
      { key: "punchOut",   label: "PUNCH OUT",  x: margin + 170, w: 55  },
      { key: "hours",      label: "HOURS",      x: margin + 225, w: 40  },
      { key: "validation", label: "VALIDATION", x: margin + 265, w: 65  },
      { key: "status",     label: "STATUS",     x: margin + 330, w: 75  },
      { key: "remark",     label: "REMARK",     x: margin + 405, w: 110 },
    ];

    const headerH = 20;
    const rowH = 34;

    const drawHeader = (startY: number) => {
      doc.rect(margin, startY, contentWidth, headerH).fill("#1e293b");
      doc.fontSize(7.5).font("Helvetica-Bold").fillColor("#e2e8f0");
      cols.forEach((col) => {
        doc.text(col.label, col.x + 3, startY + 5, {
          width: col.w - 5,
          lineBreak: false,
        });
      });
      return startY + headerH;
    };

    y = drawHeader(y);

    // ─── Rows ─────────────────────────────────────────────────────────────────
    logs.forEach((log: any, idx: number) => {
      if (y + rowH > doc.page.height - 50) {
        doc.addPage();
        y = 40;
        y = drawHeader(y);
      }

      const bg = idx % 2 === 0 ? "#f8fafc" : "#ffffff";
      doc.rect(margin, y, contentWidth, rowH).fill(bg);

      // Employee name + email
      const empName = log.employeeId?.name || "Unknown";
      const empEmail = log.employeeId?.email || "";
      doc
        .fontSize(8)
        .font("Helvetica-Bold")
        .fillColor("#0f172a")
        .text(empName, cols[0].x + 3, y + 6, {
          width: cols[0].w - 6,
          lineBreak: false,
        });
      doc
        .fontSize(6.5)
        .font("Helvetica")
        .fillColor("#64748b")
        .text(empEmail, cols[0].x + 3, y + 18, {
          width: cols[0].w - 6,
          lineBreak: false,
        });

      // Punch In
      const punchInTime = log.punchIn?.time
        ? new Date(log.punchIn.time).toLocaleTimeString("en-IN", {
            hour: "2-digit",
            minute: "2-digit",
            hour12: true,
          })
        : "-";
      doc
        .fontSize(8)
        .font("Helvetica")
        .fillColor("#0f172a")
        .text(punchInTime, cols[1].x + 3, y + 12, {
          width: cols[1].w - 5,
          lineBreak: false,
        });

      // Punch Out
      const punchOutTime = log.punchOut?.time
        ? new Date(log.punchOut.time).toLocaleTimeString("en-IN", {
            hour: "2-digit",
            minute: "2-digit",
            hour12: true,
          })
        : "-";
      doc.text(punchOutTime, cols[2].x + 3, y + 12, {
        width: cols[2].w - 5,
        lineBreak: false,
      });

      // Hours
      const hours = log.workingHours ? `${log.workingHours.toFixed(2)}h` : "-";
      doc.text(hours, cols[3].x + 3, y + 12, {
        width: cols[3].w - 5,
        lineBreak: false,
      });

      // Validation status (coloured)
      const validation = log.validation?.status || "pending";
      const valColor =
        validation === "valid"
          ? "#10b981"
          : validation === "invalid"
          ? "#ef4444"
          : "#f59e0b";
      doc
        .fillColor(valColor)
        .text(validation.toUpperCase(), cols[4].x + 3, y + 12, {
          width: cols[4].w - 5,
          lineBreak: false,
        });

      // Completion status (coloured)
      const status = log.completionStatus || "incomplete";
      const statusColor = status === "completed" ? "#10b981" : "#f59e0b";
      doc
        .fillColor(statusColor)
        .text(status.toUpperCase(), cols[5].x + 3, y + 12, {
          width: cols[5].w - 5,
          lineBreak: false,
        });

      // Remark
      const remark = log.validation?.remarks || log.remarks || "-";
      doc
        .fontSize(7)
        .fillColor("#475569")
        .text(remark, cols[6].x + 3, y + 6, {
          width: cols[6].w - 6,
          height: rowH - 10,
          ellipsis: true,
        });

      // Row divider
      doc
        .moveTo(margin, y + rowH)
        .lineTo(margin + contentWidth, y + rowH)
        .strokeColor("#e2e8f0")
        .lineWidth(0.5)
        .stroke();

      y += rowH;
    });

    // ─── Footer ───────────────────────────────────────────────────────────────
    y += 14;
    doc
      .fontSize(7.5)
      .font("Helvetica-Oblique")
      .fillColor("#94a3b8")
      .text(
        `Total ${logs.length} record(s) — Attendance Management System`,
        margin,
        y,
        { align: "center", width: contentWidth }
      );

    doc.end();
  });
};

export const generateMonthlyReportPDF = async (monthStr: string, data: any[], requestorName: string): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: "A4" });
    const buffers: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => buffers.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(buffers)));
    doc.on("error", reject);

    const pageWidth = doc.page.width;
    const margin = 40;
    const contentWidth = pageWidth - margin * 2;

    // ─── Header Banner ──────────────────────────────────────────────────────
    doc.rect(0, 0, pageWidth, 80).fill("#4f46e5");
    doc
      .fontSize(20)
      .font("Helvetica-Bold")
      .fillColor("#ffffff")
      .text("Monthly Attendance & Activity Report", margin, 18, {
        align: "center",
        width: contentWidth,
      });
    doc
      .fontSize(8.5)
      .font("Helvetica")
      .fillColor("#e0e7ff")
      .text(
        `Month: ${monthStr}  |  Generated by: ${requestorName}  |  Date: ${new Date().toLocaleDateString()}`,
        margin,
        50,
        { align: "center", width: contentWidth }
      );

    let y = 105;

    // ─── KPI Highlights Grid ───────────────────────────────────────────────
    const totalWorked = data.reduce((sum, item) => sum + item.attendance.totalWorkedHours, 0);
    const totalLeaves = data.reduce((sum, item) => sum + item.leaves.approvedDays, 0);
    const totalOT = data.reduce((sum, item) => sum + item.overtime.approvedHours, 0);

    doc.rect(margin, y, contentWidth, 50).fill("#f8fafc");
    doc.rect(margin, y, contentWidth, 50).strokeColor("#e2e8f0").lineWidth(0.5).stroke();

    doc.fontSize(8.5).font("Helvetica-Bold").fillColor("#64748b");
    doc.text("TOTAL EMPLOYEES", margin + 15, y + 12);
    doc.text("TOTAL HOURS WORKED", margin + 130, y + 12);
    doc.text("APPROVED LEAVE DAYS", margin + 265, y + 12);
    doc.text("APPROVED OVERTIME", margin + 400, y + 12);

    doc.fontSize(12).font("Helvetica-Bold").fillColor("#1e1b4b");
    doc.text(`${data.length}`, margin + 15, y + 25);
    doc.text(`${totalWorked.toFixed(1)} hrs`, margin + 130, y + 25);
    doc.text(`${totalLeaves} days`, margin + 265, y + 25);
    doc.text(`${totalOT.toFixed(1)} hrs`, margin + 400, y + 25);

    y += 75;

    // ─── Employee Summaries ────────────────────────────────────────────────
    data.forEach((item: any, idx: number) => {
      // Avoid page overflow (each card takes about 110pt)
      if (y + 110 > doc.page.height - 50) {
        doc.addPage();
        y = 40;
      }

      // Draw Card Container
      doc.rect(margin, y, contentWidth, 95).fill("#ffffff");
      doc.rect(margin, y, contentWidth, 95).strokeColor("#f1f5f9").lineWidth(0.5).stroke();

      // Header block in Card
      doc.rect(margin, y, contentWidth, 20).fill("#f1f5f9");
      doc.fontSize(8.5).font("Helvetica-Bold").fillColor("#0f172a");
      doc.text(
        `${idx + 1}. ${item.employee.name} (${item.employee.email}) - ${item.employee.role.toUpperCase()}`,
        margin + 10,
        y + 6
      );

      // Card Content: Grid values
      doc.fontSize(8).font("Helvetica").fillColor("#475569");
      
      const leftColX = margin + 15;
      const rightColX = margin + 270;
      
      doc.text(`Days Present: ${item.attendance.daysPresent}`, leftColX, y + 30);
      doc.text(`Total Worked Hours: ${item.attendance.totalWorkedHours} hrs`, leftColX, y + 42);
      doc.text(`Average Daily Hours: ${item.attendance.averageDailyHours} hrs`, leftColX, y + 54);
      doc.text(`Total Break Duration: ${item.attendance.totalBreakMinutes} mins`, leftColX, y + 66);

      doc.text(`Approved Leaves Taken: ${item.leaves.approvedDays} day(s)`, rightColX, y + 30);
      doc.text(`Pending Leave Requests: ${item.leaves.pendingRequests}`, rightColX, y + 42);
      doc.text(`Approved Overtime Hours: ${item.overtime.approvedHours} hrs`, rightColX, y + 54);
      doc.text(`Pending Overtime Requests: ${item.overtime.pendingRequests}`, rightColX, y + 66);

      y += 105;
    });

    // ─── Footer ───────────────────────────────────────────────────────────────
    if (y + 30 > doc.page.height - 50) {
      doc.addPage();
      y = 40;
    }
    doc
      .fontSize(7.5)
      .font("Helvetica-Oblique")
      .fillColor("#94a3b8")
      .text(
        `Generated on ${new Date().toLocaleString()}  |  Attendance Management System`,
        margin,
        y + 10,
        { align: "center", width: contentWidth }
      );

    doc.end();
  });
};
